CREATE DATABASE mcsharesDB;

DROP TABLE IF EXISTS T_CUSTOMERS;
CREATE TABLE T_CUSTOMERS (
    ID_CUSTOMER INT PRIMARY KEY,
    BOO_DELETED BIT,
    DATE_CREATE DATE,
    DATE_UPDATE DATE,
    CUSTOMER_REF VARCHAR(255),
    CUSTOMER_TYPE VARCHAR(255),
    DATE_OF_BIRTH DATE,
    DATE_INCORP DATE,
    NO_REGISTRATION VARCHAR(255),
    ID_MAILING_ADDRESS INT,
    ID_CONTACT_DETAILS INT,
    ID_SHARES_DETAILS INT
);

DROP TABLE IF EXISTS T_CONTACT_DETAILS;
CREATE TABLE T_CONTACT_DETAILS (
    ID_CONTACT_DETAILS INT PRIMARY KEY,
    BOO_DELETED BIT,
    DATE_CREATE DATE,
    DATE_UPDATE DATE,
    CONTACT_NAME VARCHAR(255),
    CONTACT_NUMBER VARCHAR(255)
);

DROP TABLE IF EXISTS T_MAILING_ADDRESS;
CREATE TABLE T_MAILING_ADDRESS (
    ID_MAILING_ADDRESS INT PRIMARY KEY,
    BOO_DELETED BIT,
    DATE_CREATE DATE,
    DATE_UPDATE DATE,
    TXT_ADDRESS_1 VARCHAR(255),
    TXT_ADDRESS_2 VARCHAR(255),
    TXT_TOWN_CITY VARCHAR(255),
    TXT_COUNTRY VARCHAR(255)
);

DROP TABLE IF EXISTS T_SHARES_DETAILS;
CREATE TABLE T_SHARES_DETAILS (
    ID_SHARES_DETAILS INT PRIMARY KEY,
    BOO_DELETED BIT,
    DATE_CREATE DATE,
    DATE_UPDATE DATE,
    NUM_SHARES INT,
    SHARE_PRICE FLOAT
);

DROP TABLE IF EXISTS T_ERROR_LOG;
CREATE TABLE T_ERROR_LOG (
    ID_ERROR_LOG INT PRIMARY KEY,
    BOO_DELETED BIT,
    DATE_CREATE DATE,
    DATE_UPDATE DATE,
    CUSTOMER_REF VARCHAR(255),
    TXT_ERROR_DESCRIPTION VARCHAR(255),
    TXT_FILENAME VARCHAR(255)
);